<?php include('Partials/header.php'); ?>
  <main>
    <div class="container">
      <h1>Le début des haricots ASBL</h1>
      <p style="text-align: justify;">L’association «&nbsp;Le début des haricots&nbsp;» s’occupe depuis 2005 de lutter pour la protection de l’environnement, la mobilisation et la sensibilisation&nbsp;citoyenne, l’économie sociale par rapport aux problématiques de la pollution et des dérives du système industriel. L’association a défini le thème de l’alimentation comme l’une de ses priorités.</p>
      <p style="text-align: justify;">L’association à&nbsp;participé&nbsp;à la naissance des «&nbsp;<a href="http://www.potagersurbains.be/" target="_blank">jardins collectifs</a>&nbsp;»&nbsp;à Bruxelles et elle gère actuellement leur mise en&nbsp;réseau&nbsp;et l’aide à leur mise en place. L’idée des jardins collectifs est de se ré-approprier&nbsp;des terres encore disponibles en ville (friches, parcs, etc.) en luttant contre la pression immobilière, pour tisser du lien social dans les quartiers et reconnecter le citoyen à l’alimentation saine à travers l’auto-production. Aujourd’hui Bruxelles compte plus de 60 jardins collectifs.</p>
      <button id="js_readme_home" class="btn btn-success">En savoir plus</button>
      <div class="para_read">
        <p style="text-align: justify;">L’association a propulsé la création du&nbsp;réseau&nbsp;des&nbsp;<a href="http://www.gasap.be" target="_blank">GASAP</a>&nbsp;(Groupe d’achat solidaire à l’agriculture paysanne), où des producteurs des campagnes aux alentours de Bruxelles s’organisent avec des&nbsp;consommateurs&nbsp;en ville pour créer une filière courte de produits sains et de saison. Le contrat est établi au début de la saison, ce qui permet aux producteurs la pré-vente de toute la production et donc leur sécurité financière. Actuellement Bruxelles compte plus de 40 GASAP actifs !</p>
        <p style="text-align: justify;">Nous avons choisi de nous adresser également à un public plus jeune,&nbsp;auprès de milieux plus défavorisés, à travers l’éducation à l’environnement proposée par le projet «&nbsp;<a href="http://www.haricots.org/?q=content/les-projets-p-dagogiques-deducation-relative-l-environnement-ere/16" target="_blank">Jardins des couleurs</a>«&nbsp;, qui se déroule dans les écoles et écoles de devoir de Bruxelles. Nous enseignons aux enfants et aux adultes des techniques de jardinage simples (pour encourager l’autoproduction), tout en menant un débat plus théorique sur les liens entre nos actions quotidiennes et notre empreinte écologique.</p>
        <p style="text-align: justify;">En ce qui concerne l’agriculture urbaine nous avons crée le projet de la «&nbsp;<a href="http://www.haricots.org/?q=agriculture/NOH-020209" target="_blank">Ferme Urbaine</a>«&nbsp;, dans la périphérie de Bruxelles, à Neder-Over-Hembeek. Une ferme agro-écologique qui forme 4 jeunes peu qualifiés et au chômage au maraichage biologique, et qui approvisionne et livre les 40 paniers a un GASAP local…transportés chaque semaine sur le dos des deux&nbsp;ânesses&nbsp;de la ferme !</p>
        <p style="text-align: justify;">Un autre projet tout nouveau est la «&nbsp;<a href="http://www.chantdescailles.be" target="_blank">Ferme du chant des cailles</a>&nbsp;» à Watermael-Boisfort, où &nbsp;sur une superficie de 2.9ha s’installent un maraîcher et un éleveur de brebis laitières, en totale autonomie financière.</p>
        <p style="text-align: justify;">En plus de toutes ces actions urbaines nous avons participé aussi à la création de l’association «&nbsp;<a title="Terre en vue ASBL" href="http://www.terre-en-vue.be" target="_blank">Terre en vue</a>«&nbsp;, qui s’occupe de preserver les terres de Belgique pour la création de fermes agro-écologique.</p>
        <p>Pour plus d’info vous pouvez visiter notre site web: <a title="DDH" href="http://www.haricots.org" target="_blank">http://www.haricots.org</a></p>
      </div>
    </div>
  </main> 
<?php include('Partials/footer.php'); ?>